星 矩形

#include<iostream>
#include<string>
using namespace std;
#include<ctime>

int main()
{

	for (int i = 0; i < 10; i++)
	{
		for (int i = 0; i < 10; i++)
		{
			cout <<"* ";
		}
		cout << endl;
	}

	

	system("pause");
	return 0;
}

乘法口诀

#include<iostream>
#include<string>
using namespace std;
#include<ctime>

int main()
{
	for (int i = 1; i <=9; i++)
	{
		//cout << i << endl;
		for (int j = 1; j <= i; j++)
		{
			cout << j<<"*"<<i<<"="<<j*i<<"  ";
		}
		cout << endl;
	}


	system("pause");
	return 0;
}



continue语句：跳过当前程序以下的操作，执行下一步循环

	for (int i = 1; i <=100; i++)
	{
		if (i % 2 == 0)
		{
			continue;
		}
		cout << i << endl;
	}
