星 矩形

#include<iostream>
#include<string>
using namespace std;
#include<ctime>

int main()
{

	for (int i = 0; i < 10; i++)
	{
		for (int i = 0; i < 10; i++)
		{
			cout <<"* ";
		}
		cout << endl;
	}

	

	system("pause");
	return 0;
}
